apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ include "frontend.name" . }}
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31000
